# configs for Snakemake and where they are stored
snakemake_logs_dir: /allen/aics/assay-dev/computational/data/EMT_deliverable_processing/Collagen_segmentation_segmentations/Snakemake_logs/EOMES_TBR2
# Output directory- location in your filesystem where you want to store the output
output_parent_dir: /allen/aics/assay-dev/computational/data/EMT_deliverable_processing/Collagen_segmentation_segmentations/EOMES_TBR2
# Working directory- location in your filesystem where your code is stored
working_dir: /allen/aics/assay-dev/users/Goutham/EMT_deliverable_processing
# logdir for snakemake
runtime_snakemake_logdir: /allen/aics/assay-dev/computational/data/EMT_deliverable_processing/LOGS/batch_processing_logs 
# CytoDL output directory
output_segmentation_dir: /allen/aics/assay-dev/computational/data/EMT_deliverable_processing/cytodl_experiments/logs/eval/runs/basement_membrane_semseg_reproducibility_run/basement_membrane_semseg_reproducibility_run/2024-07-12_15-33-16/predict_images 




