# configs for Snakemake and where they are stored. This is what is created using create_BM_snakemake_configs.py
snakemake_logs_dir: /allen/aics/assay-dev/computational/data/EMT_deliverable_processing/Collagen_segmentation_segmentations/Snakemake_logs/HIST1H2BJ
# output parent directory- location in your filesystem where you want to store the output
output_dir: /allen/aics/assay-dev/computational/data/EMT_deliverable_processing/Collagen_segmentation_segmentations/HIST1H2BJ
# Working directory- location in your filesystem where your code is stored
working_dir: /allen/aics/assay-dev/users/Goutham/EMT_image_analysis/basement_membrane_segmentation/processing_workflow
# structure
structure_name: "HIST1H2BJ"
# data manifest(From Antoine)
data_manifest: /allen/aics/assay-dev/computational/data/EMT_deliverable_processing/Collagen_segmentation_segmentations/EMT_deliverable_1_dataset_1_with_aligned_path_info.csv
# logdir for snakemake
runtime_snakemake_logdir: /allen/aics/assay-dev/computational/data/EMT_deliverable_processing/LOGS/batch_processing_logs





