model:
  _target_: cyto_dl.models.im2im.MultiTaskIm2Im
  save_images_every_n_epochs: 50
  save_dir: .//data//bf_colony_seg/eval_whole_movie_multiscale_256_antoine_g6_sg1
  x_key: raw
  backbone:
    _target_: monai.networks.nets.DynUNet
    spatial_dims: 3
    in_channels: 1
    out_channels: 1
    strides:
    - 1
    - 2
    - 2
    - 2
    kernel_size:
    - 3
    - 3
    - 3
    - 3
    upsample_kernel_size:
    - 2
    - 2
    - 2
    dropout: 0.0
    res_block: true
  task_heads:
    seg:
      _target_: cyto_dl.nn.BaseHead
      loss:
        _target_: monai.losses.GeneralizedDiceFocalLoss
        sigmoid: true
      postprocess:
        input:
          _target_: cyto_dl.models.im2im.utils.postprocessing.ActThreshLabel
          rescale_dtype: numpy.uint8
        prediction:
          _target_: cyto_dl.models.im2im.utils.postprocessing.ActThreshLabel
          activation:
            _target_: torch.nn.Sigmoid
          rescale_dtype: numpy.uint8
      save_input: true
  optimizer:
    generator:
      _partial_: true
      _target_: torch.optim.Adam
      lr: 0.0001
      weight_decay: 0.0001
  lr_scheduler:
    generator:
      _partial_: true
      _target_: torch.optim.lr_scheduler.ExponentialLR
      gamma: 0.995
  inference_args:
    sw_batch_size: 1
    roi_size:
    - 16
    - 256
    - 256
  compile: true
model/params/total: 5644897
model/params/trainable: 5644897
model/params/non_trainable: 0
data:
  _target_: cyto_dl.datamodules.czi.make_CZI_dataloader
  num_workers: 1
  batch_size: 1
  pin_memory: true
  persistent_workers: false
  csv_path: .//data//bf_colony_seg/predict_bf_multiscale_v1_g6_sg1.csv
  img_path_column: movie_path
  channel_column: bf_channel
  fms_id_column: fms_id
  out_key: raw
  transforms:
  - _target_: monai.transforms.ToTensor
  - _target_: monai.transforms.NormalizeIntensity
trainer:
  _target_: lightning.Trainer
  default_root_dir: /allen/aics/assay-dev/users/Sandi/cyto-dl/logs/eval/runs/fijimasks_cytogfp_test_vXXX/v2_multiscale_antoine_test_whole_movie_g6_sg1_256/2024-07-20_22-35-39
  min_epochs: 1
  max_epochs: 1000
  accelerator: gpu
  devices:
  - 0
  precision: 16
  check_val_every_n_epoch: 1
  deterministic: false
  detect_anomaly: false
  max_time: null
callbacks:
  model_checkpoint:
    _target_: lightning.pytorch.callbacks.ModelCheckpoint
    dirpath: /allen/aics/assay-dev/users/Sandi/cyto-dl/logs/eval/runs/fijimasks_cytogfp_test_vXXX/v2_multiscale_antoine_test_whole_movie_g6_sg1_256/2024-07-20_22-35-39/checkpoints
    filename: epoch_{epoch:03d}
    monitor: train/loss
    verbose: false
    save_last: true
    save_top_k: 1
    mode: min
    auto_insert_metric_name: false
    save_weights_only: false
    every_n_train_steps: null
    train_time_interval: null
    every_n_epochs: 1
    save_on_train_epoch_end: null
  model_summary:
    _target_: lightning.pytorch.callbacks.RichModelSummary
    max_depth: -1
  rich_progress_bar:
    _target_: lightning.pytorch.callbacks.RichProgressBar
  early_stopping:
    monitor: val/loss
    patience: 100
    mode: min
extras:
  ignore_warnings: true
  enforce_tags: true
  print_config: true
  precision:
    _target_: torch.set_float32_matmul_precision
    precision: medium
task_name: eval
tags:
- dev
ckpt_path: /allen/aics/assay-dev/users/Sandi/cyto-dl/logs/train/runs/fijimasks_cytogfp_ALL_v3/v3/2024-03-23_14-33-36/checkpoints/epoch_426.ckpt
seed: 12345
