# @package _global_
# to execute this experiment run:
# python train.py experiment=example
defaults:
  - override /data: local/whole_movie.yaml
  - override /model: local/segmentation_ms25.yaml
  - override /callbacks: default.yaml
  - override /trainer: gpu.yaml
  - override /logger: mlflow.yaml

# all parameters below will be merged with parameters from default configurations set above
# this allows you to overwrite only specified parameters

tags: ["dev"]
seed: 12345

experiment_name: train_cytogfp_seg_model_v0
run_name: test_v0_patch1
source_col: raw
target_col: seg
spatial_dims: 3
raw_im_channels: 1
ckpt_path: /allen/aics/assay-dev/users/Sandi/cyto-dl/logs/train/runs/fijimasks_cytogfp_ALL_v3/v3/2024-03-23_14-33-36/checkpoints/epoch_426.ckpt
trainer:
  max_epochs: 1000
  devices: [0]

model:
  compile: True
  save_dir: ${paths.data_dir}/all_cells_mask_test_dir/eval_whole_movie_multiscale_patch1

data:
  csv_path: ${paths.data_dir}/all_cells_mask_test_dir/predict_all_cells_mask_v0.csv
  batch_size: 1
  _aux: 
    patch_shape: [16, 128, 128]