# @package _global_
# to execute this experiment run:
# python train.py experiment=example
defaults:
  - override /data: local/segmentation_bf.yaml
  - override /model: local/segmentation_ms25.yaml
  - override /callbacks: default.yaml
  - override /trainer: gpu.yaml
  - override /logger: mlflow.yaml

# all parameters below will be merged with parameters from default configurations set above
# this allows you to overwrite only specified parameters

tags: ["dev"]
seed: 12345

experiment_name: train_cytogfp_seg_model_v0
# persist_cahce: False
run_name: test_v0
source_col: raw
target_col: seg
spatial_dims: 3
raw_im_channels: 1
#ckpt_path: /allen/aics/assay-dev/users/Sandi/cyto-dl/logs/train/runs/fijimasks_cytogfp_ALL_v3/v3/2024-03-22_16-12-46/checkpoints/epoch_425.ckpt
trainer:
  max_epochs: 10000
  devices: [0]

model:
  compile: True
#  patch_shape: [32, 128, 128]

data:
  path: ${paths.data_dir}/all_cells_mask_test_dir/train_val
  cache_dir: ${paths.data_dir}/all_cells_mask_test_dir/train_val/cache
  #subsample: 
  #  train: 100
  batch_size: 128
  _aux: 
    patch_shape: [16, 128, 128]

